### ISSUE TITLE
assn1 Makefile 변경 요청

### ISSUE THREAD

**Issue by saygenie** [jeonhyun97/cpp_4_undergraduates#1]
https://github.com/jeonhyun97/cpp_4_undergraduates/blob/ac1e2020e02128b5bb996d43f17bc7ff79a3950c/cpp/assn/assn1/code/Makefile#L5

assn1 과제를 할 때, `main.cpp`를 수정하지 않고 `main.answer.cpp`로 동작하게끔 만들면 어떨까요? 로컬에서 확인을 할 때 불필요하게 커밋하는 일을 막을 수 있을 것 같습니다.

**Comment by hj-n** [comment]
ok

**Comment by hj-n** [comment]
accepted

**Comment by saygenie** [comment]
thx!
